condense.data.frame <- function(data) {
  ##This is a way to condense data frames that consist of highly repetetive data
  ##(such as are often generated by my experiment.)
  
  column.names <- colnames(data)
  data.matches <- colwise(function(x) match(x,x))(data)
  lookup <- mapply(function(m, d) d[unique(m)], data.matches, data)
  data.matches <- colwise(function(x)as.numeric(factor(x)))(data.matches)
  column.matches <- match(data.matches,data.matches)
  column.matches <- column.names[column.matches]
  names(column.matches) <- column.names
  min.columns <- column.matches[!duplicated(column.matches)]
  data.matches <- data.matches[,min.columns]
  list(data=data.matches, columns=column.matches, lookup=lookup)
}

uncondense.data.frame <- function(condensed) {
  ##The inverse of condense.data.frame.
  data <- 
}
